// --- AUTO-GENERATED BY BOOTLOADER ---

/* --- DESKTOP ENVIRONMENT --- */
#define VOX_PLATFORM_DESKTOP
#if defined(__APPLE__)
    #define VOX_PLATFORM_MAC
#elif defined(__linux__)
    #define VOX_PLATFORM_LINUX
#elif defined(_WIN32)
    #define VOX_PLATFORM_WINDOWS
#endif

#include <stdlib.h>
#include <stdbool.h>
#define VOX_MALLOC(size) malloc(size)
#define VOX_FREE(ptr)    free(ptr)

// --- SYSTEM TYPES ---
#define VOX_BUS_EVENT_STRING 0
#define VOX_BUS_EVENT_BUFFER 1
#define VOX_BUS_EVENT_SIGNAL 2
typedef bool (*VoxEventBusTransmit)(const int type, const void* payload, const int size, const char* source);

// --- TASK INTERFACES ---
#define VOX_TASK(name, prefix) \
    static inline void prefix##_boot(VoxEventBusTransmit transmit); \
    static inline void prefix##_terminate(void); \
    static inline void prefix##_run(float delta_time); \
    static inline bool prefix##_on_event_bus(const int type, const void* payload, const int size, const char* source);

#define VOX_TASK_STACK \
    VOX_TASK(task_ui_terminal_desktop, task_ui_terminal_desktop) \
    VOX_TASK(task_output_radio_desktop, task_output_radio_desktop) \
    VOX_TASK(task_output_keys_mac, task_output_keys_mac) \
    VOX_TASK(task_input_data_enviorment_desktop, task_input_data_enviorment_desktop) \
    VOX_TASK(task_input_speech_desktop, task_input_speech_desktop) \
    VOX_TASK(task_trans_intent_fuzzy_universal, task_trans_intent_fuzzy_universal) \

VOX_TASK_STACK
#undef VOX_TASK

// --- AUTO-INCLUDES ---
#include "task_ui_terminal_desktop.c"
#include "task_output_radio_desktop.c"
#include "task_output_keys_mac.c"
#include "task_input_data_enviorment_desktop.c"
#include "task_input_speech_desktop.c"
#include "task_trans_intent_fuzzy_universal.c"
