// --- AUTO-GENERATED BY BOOTLOADER ---

#include <ctype.h>
#ifdef DEBUG
    #define VOX_DEBUG 1
#else
    #define VOX_DEBUG 0
#endif

#define VOX_STRING_COPY(src, dst, size)             \
    do {                                            \
        const char* s = (const char*)(src);         \
        int i = 0;                                  \
        for (; s[i] && i < (size) - 1; i++)          \
            dst[i] = s[i];                          \
        dst[i] = 0;                                 \
    } while (0)

#define VOX_STRING_LENGTH(src, out_len)             \
    do {                                            \
        const char* s = (const char*)(src);         \
        int i = 0;                                  \
        for (; s[i]; i++)                           \
            ;                                       \
        (out_len) = i;                              \
    } while (0)

#define VOX_STRING_TRIM(str, size)                  \
    do {                                            \
        char* s_p = (char*)(str);                   \
        int s_s = 0;                                \
        while (s_p[s_s] && (s_p[s_s] == ' ' || s_p[s_s] == '\t' || s_p[s_s] == '\n' || s_p[s_s] == '\r')) \
            s_s++;                                  \
        int s_e = s_s;                              \
        while (s_p[s_e])                            \
            s_e++;                                  \
        while (s_e > s_s && (s_p[s_e-1] == ' ' || s_p[s_e-1] == '\t' || s_p[s_e-1] == '\n' || s_p[s_e-1] == '\r')) \
            s_e--;                                  \
        int new_len = s_e - s_s;                    \
        if (s_s > 0) {                              \
            for (int k = 0; k < new_len; k++)       \
                s_p[k] = s_p[k + s_s];              \
        }                                           \
        s_p[new_len] = '\0';                     \
    } while (0)

#define VOX_STRING_LOWER(str, size)                 \
    do {                                            \
        for (int i = 0; str[i] && i < (size) - 1; i++)\
            str[i] = (char)tolower((unsigned char)str[i]); \
    } while (0)

#define VOX_STRING_COMPARE(str1, str2, size, out_match) \
    do {                                            \
        const char* s_1 = (const char*)(str1);      \
        const char* s_2 = (const char*)(str2);      \
        int c_i = 0;                                \
        (out_match) = 1;                            \
        while (c_i < (size)) {                      \
            if (s_1[c_i] != s_2[c_i]) {             \
                (out_match) = 0;                    \
                break;                              \
            }                                       \
            if (s_1[c_i] == '\0') break;             \
            c_i++;                                  \
        }                                           \
    } while (0)

#define VOX_STRING_LOWER_UNTIL_ANY(str, size, stops)  \
    do {                                            \
        int stop_f = 0;                             \
        for (int i = 0; str[i] && i < (size) - 1; i++) { \
            for (int j = 0; stops[j]; j++) {        \
                if (str[i] == stops[j]) { stop_f = 1; break; } \
            }                                       \
            if (stop_f) break;                      \
            str[i] = (char)tolower((unsigned char)str[i]); \
        }                                           \
    } while (0)
#define VOX_STRING_STARTS_WITH(str, prefix, res)     \
    do {                                            \
        int i = 0;                                  \
        res = 1;                                    \
        while (prefix[i]) {                         \
            if (str[i] != prefix[i]) {              \
                res = 0;                            \
                break;                              \
            }                                       \
            i++;                                    \
        }                                           \
    } while (0)
#define VOX_STRING_CHOP_UNTIL_INDEX(str, index)       \
    do {                                            \
        int idx = (index);                          \
        int i = 0;                                  \
        while (str[idx + i]) {                      \
            str[i] = str[idx + i];                  \
            i++;                                    \
        }                                           \
        str[i] = 0;                                 \
    } while (0)

#define VOX_STRING_CHOP_UNTIL_ANY(str, stops)       \
    do {                                            \
        int found_idx = -1;                         \
        for (int i = 0; str[i]; i++) {              \
            for (int j = 0; stops[j]; j++) {        \
                if (str[i] == stops[j]) {           \
                    found_idx = i + 1; break;       \
                }                                   \
            }                                       \
            if (found_idx != -1) break;             \
        }                                           \
        if (found_idx != -1) {                      \
            int k = 0;                              \
            while (str[found_idx + k]) {            \
                str[k] = str[found_idx + k];        \
                k++;                                \
            }                                       \
            str[k] = 0;                             \
        }                                           \
    } while (0)
/* --- DESKTOP ENVIRONMENT --- */
#define VOX_PLATFORM_DESKTOP
#if defined(__APPLE__)
    #define VOX_PLATFORM_MAC
#elif defined(__linux__)
    #define VOX_PLATFORM_LINUX
#elif defined(_WIN32)
    #define VOX_PLATFORM_WINDOWS
#endif

#include <stdlib.h>
#include <stdbool.h>
#define VOX_MALLOC(size) malloc(size)
#define VOX_FREE(ptr)    free(ptr)

// --- SYSTEM TYPES ---
#define VOX_BUS_EVENT_STRING 0
#define VOX_BUS_EVENT_MIC_POINTER 50
#define VOX_BUS_EVENT_BUFFER 1
#define VOX_BUS_EVENT_SIGNAL 2
typedef bool (*VoxEventBusTransmit)(int type, void* payload, int size, char* source);

// --- TASK INTERFACES ---
#define VOX_TASK(name, prefix) \
    static inline void prefix##_boot(VoxEventBusTransmit transmit); \
    static inline void prefix##_terminate(void); \
    static inline void prefix##_run(float delta_time); \
    static inline bool prefix##_on_event_bus(int type, void* payload, int size, char* source);

#define VOX_TASK_STACK \
    VOX_TASK(task_ui_terminal_desktop, task_ui_terminal_desktop) \
    VOX_TASK(task_input_data_enviorment_desktop, task_input_data_enviorment_desktop) \
    VOX_TASK(task_input_microphone_port_audio_desktop, task_input_microphone_port_audio_desktop) \
    VOX_TASK(task_input_speech_vosk_desktop, task_input_speech_vosk_desktop) \
    VOX_TASK(task_trans_intent_fuzzy_universal, task_trans_intent_fuzzy_universal) \
    VOX_TASK(task_output_radio_mpv_desktop, task_output_radio_mpv_desktop) \
    VOX_TASK(task_output_keys_desktop, task_output_keys_desktop) \

VOX_TASK_STACK
#undef VOX_TASK

// --- AUTO-INCLUDES ---
#include "task_ui_terminal_desktop.c"
#include "task_input_data_enviorment_desktop.c"
#include "task_input_microphone_port_audio_desktop.c"
#include "task_input_speech_vosk_desktop.c"
#include "task_trans_intent_fuzzy_universal.c"
#include "task_output_radio_mpv_desktop.c"
#include "task_output_keys_desktop.c"
