#!/bin/bash

# Force the script to run from its own directory
cd "$(dirname "$0")" || exit 1

# Build folder
mkdir -p Build
cd Source || { echo "Fatal Error: 'Source' folder not found!"; exit 1; }

# Build Name: Parse 
# defaults to vox_core
BUILD_NAME="${1:-vox_core}"
shift

# Platform: Parse
PLATFORM=""
for arg in "$@"; do
    if [[ $arg == --platform=* ]]; then
        PLATFORM="${arg#*=}"
    fi
done

# Build Mode: Parse
BUILD_MODE="debug"
for arg in "$@"; do
    if [[ $arg == --mode=* ]]; then
        BUILD_MODE="${arg#*=}"
    fi
done

# Build Mode: Configure Flags
if [ "$BUILD_MODE" == "debug" ]; then
    BUILD_MODE_FLAGS="-g -O0 -DDEBUG"
elif [ "$BUILD_MODE" == "release" ]; then
    BUILD_MODE_FLAGS="-O3 -DNDEBUG"
else
    echo "Fatal Error: Unknown build mode '$BUILD_MODE'."
    echo "Valid modes are --mode=debug or --mode=release"
    exit 1
fi

# Platform: Validate
if [ -z "$PLATFORM" ]; then
    echo "Fatal Error: No platform specified!"
    echo "You must declare a target platform."
    echo "Example: vox_build vox_core --platform=desktop --task_.... --task_... ...."
    exit 1
fi

# Detect Sub-Platform for Desktop Inheritance
SUB_PLATFORM=""
if [[ "$PLATFORM" == "desktop" ]]; then
    case "$(uname -s)" in
        Darwin*) SUB_PLATFORM="mac" ;;
        Linux*)  SUB_PLATFORM="linux" ;;
        CYGWIN*|MINGW*|MSYS*) SUB_PLATFORM="windows" ;;
    esac
fi

# Tasks: Parse (Keeps the 'task_' prefix)
TASKS=()
for arg in "$@"; do
    if [[ $arg == --task_* ]]; then
        TASKS+=("${arg:2}")
    fi
done

# Tasks: Validate
if [ ${#TASKS[@]} -eq 0 ]; then
    echo "Fatal Error: No explicit tasks provided!"
    echo "You must specify at least one task to build."
    echo "Example: vox_build vox_core --platform=desktop --task_.... --task_... ...."
    exit 1
fi

# Tasks: files
TASK_FILES=()
for task in "${TASKS[@]}"; do
    TASK_FILES+=("$task.c")
done

# Tasks: dependency harvester
DEPS=""
while read -r raw_line; do
    if [[ "$raw_line" == *":"* ]]; then
        platforms="${raw_line%%:*}"
        packages="${raw_line#*:}"        
        if [[ " $platforms " == *" $PLATFORM "* ]] || [[ -n "$SUB_PLATFORM" && " $platforms " == *" $SUB_PLATFORM "* ]]; then
            DEPS="$DEPS $packages"
        fi
    else
        DEPS="$DEPS $raw_line"
    fi
done < <(grep -h "// [V]OX_DEP:" "${TASK_FILES[@]}" 2>/dev/null | sed 's/.*VOX_DEP: //' | tr -d '\r')

# Tasks: package harvester
SYS_PKGS=""
while read -r raw_line; do
    if [[ "$raw_line" == *":"* ]]; then
        platforms="${raw_line%%:*}"
        packages="${raw_line#*:}"
        if [[ " $platforms " == *" $PLATFORM "* ]] || [[ -n "$SUB_PLATFORM" && " $platforms " == *" $SUB_PLATFORM "* ]]; then 
            SYS_PKGS="$SYS_PKGS $packages"
        fi
    else
        SYS_PKGS="$SYS_PKGS $raw_line"
    fi
done < <(grep -h "// [V]OX_PKG:" "${TASK_FILES[@]}" 2>/dev/null | sed 's/.*VOX_PKG: //' | tr -d '\r')

# Tasks: package guard
if ! command -v brew &> /dev/null; then
    echo "Fatal Error: Homebrew is required but not installed."
    exit 1
fi

# Tasks: package resolver
for pkg in $SYS_PKGS; do
    if ! brew list "$pkg" &>/dev/null; then
        read -p "Warning: '$pkg' is missing. Its needed to complete build. Install it ? [Y/n] " choice
        case "$choice" in 
            # Install
            [yY]* | "" ) 
            
                echo "Installing $pkg..."
                if ! brew install "$pkg"; then
                    echo "Fatal Error: Homebrew failed to install '$pkg'. Check your connection."
                    exit 1
                fi
                ;;
            # : User declined or typed gibberish
            * ) 
                echo "Fatal Error: Build aborted. Cannot proceed without '$pkg'."
                exit 1 
                ;;
        esac
    fi
done

# Tasks: dependency resolver
if [ ! -z "$DEPS" ]; then
    SEARCH_PATHS="-I/opt/homebrew/include -L/opt/homebrew/lib -I/usr/local/include -L/usr/local/lib"
    FLAGS="$SEARCH_PATHS $DEPS"
else
    FLAGS=""
fi

# Tasks & Platform: Auto-generate configuration source
{
    printf "// --- AUTO-GENERATED BY BOOTLOADER ---\n\n"

    # Global Utilities
    printf "#include <ctype.h>\n"

    printf "#define VOX_STRING_COPY(src, dst, size)             \\\\\n"
    printf "    do {                                            \\\\\n"
    printf "        const char* s = (const char*)(src);         \\\\\n"
    printf "        int i = 0;                                  \\\\\n"
    printf "        for (; s[i] && i < (size) - 1; i++)          \\\\\n"
    printf "            dst[i] = s[i];                          \\\\\n"
    printf "        dst[i] = 0;                                 \\\\\n"
    printf "    } while (0)\n\n"

    printf "#define VOX_STRING_LOWER(str, size)                 \\\\\n"
    printf "    do {                                            \\\\\n"
    printf "        for (int i = 0; str[i] && i < (size) - 1; i++)\\\\\n"
    printf "            str[i] = (char)tolower((unsigned char)str[i]); \\\\\n"
    printf "    } while (0)\n\n"

    printf "#define VOX_STRING_LOWER_UNTIL_ANY(str, size, stops)  \\\\\n"
    printf "    do {                                            \\\\\n"
    printf "        int stop_f = 0;                             \\\\\n"
    printf "        for (int i = 0; str[i] && i < (size) - 1; i++) { \\\\\n"
    printf "            for (int j = 0; stops[j]; j++) {        \\\\\n"
    printf "                if (str[i] == stops[j]) { stop_f = 1; break; } \\\\\n"
    printf "            }                                       \\\\\n"
    printf "            if (stop_f) break;                      \\\\\n"
    printf "            str[i] = (char)tolower((unsigned char)str[i]); \\\\\n"
    printf "        }                                           \\\\\n"
    printf "    } while (0)\n"

    printf "#define VOX_STRING_STARTS_WITH(str, prefix, res)     \\\\\n"
    printf "    do {                                            \\\\\n"
    printf "        int i = 0;                                  \\\\\n"
    printf "        res = 1;                                    \\\\\n"
    printf "        while (prefix[i]) {                         \\\\\n"
    printf "            if (str[i] != prefix[i]) {              \\\\\n"
    printf "                res = 0;                            \\\\\n"
    printf "                break;                              \\\\\n"
    printf "            }                                       \\\\\n"
    printf "            i++;                                    \\\\\n"
    printf "        }                                           \\\\\n"
    printf "    } while (0)\n"
    
    printf "#define VOX_STRING_CHOP_UNTIL_INDEX(str, index)       \\\\\n"
    printf "    do {                                            \\\\\n"
    printf "        int idx = (index);                          \\\\\n"
    printf "        int i = 0;                                  \\\\\n"
    printf "        while (str[idx + i]) {                      \\\\\n"
    printf "            str[i] = str[idx + i];                  \\\\\n"
    printf "            i++;                                    \\\\\n"
    printf "        }                                           \\\\\n"
    printf "        str[i] = 0;                                 \\\\\n"
    printf "    } while (0)\n\n"

    printf "#define VOX_STRING_CHOP_UNTIL_ANY(str, stops)       \\\\\n"
    printf "    do {                                            \\\\\n"
    printf "        int found_idx = -1;                         \\\\\n"
    printf "        for (int i = 0; str[i]; i++) {              \\\\\n"
    printf "            for (int j = 0; stops[j]; j++) {        \\\\\n"
    printf "                if (str[i] == stops[j]) {           \\\\\n"
    printf "                    found_idx = i + 1; break;       \\\\\n"
    printf "                }                                   \\\\\n"
    printf "            }                                       \\\\\n"
    printf "            if (found_idx != -1) break;             \\\\\n"
    printf "        }                                           \\\\\n"
    printf "        if (found_idx != -1) {                      \\\\\n"
    printf "            int k = 0;                              \\\\\n"
    printf "            while (str[found_idx + k]) {            \\\\\n"
    printf "                str[k] = str[found_idx + k];        \\\\\n"
    printf "                k++;                                \\\\\n"
    printf "            }                                       \\\\\n"
    printf "            str[k] = 0;                             \\\\\n"
    printf "        }                                           \\\\\n"
    printf "    } while (0)\n"
    
    # Platform Flags & Memory Mapping: Desktop
    if [ "$PLATFORM" == "desktop" ]; then
        printf '/* --- DESKTOP ENVIRONMENT --- */\n'
        printf '#define VOX_PLATFORM_DESKTOP\n'
        printf '#if defined(__APPLE__)\n'
        printf '    #define VOX_PLATFORM_MAC\n'
        printf '#elif defined(__linux__)\n'
        printf '    #define VOX_PLATFORM_LINUX\n'
        printf '#elif defined(_WIN32)\n'
        printf '    #define VOX_PLATFORM_WINDOWS\n'
        printf '#endif\n\n'
        
        printf '#include <stdlib.h>\n'
        printf '#include <stdbool.h>\n'
        printf '#define VOX_MALLOC(size) malloc(size)\n'
        printf '#define VOX_FREE(ptr)    free(ptr)\n\n'
    
    # Platform Flags & Memory Mapping: Esp32
    elif [ "$PLATFORM" == "esp32" ]; then
        printf '/* --- ESP32 ENVIRONMENT --- */\n'
        printf '#define VOX_PLATFORM_ESP32\n\n'
        
        printf '#include <stdbool.h>\n'
        printf '#include "freertos/FreeRTOS.h"\n'
        printf '#define VOX_MALLOC(size) pvPortMalloc(size)\n'
        printf '#define VOX_FREE(ptr)    vPortFree(ptr)\n\n'
    fi

    # System Types
    printf '// --- SYSTEM TYPES ---\n'
    printf '#define VOX_BUS_EVENT_STRING 0\n'
    printf '#define VOX_BUS_EVENT_MIC_POINTER 50\n'
    printf '#define VOX_BUS_EVENT_BUFFER 1\n'
    printf '#define VOX_BUS_EVENT_SIGNAL 2\n'
    printf 'typedef bool (*VoxEventBusTransmit)(const int type, const void* payload, const int size, const char* source);\n\n'

   # Forward Declarations (The Rule)
    printf '// --- TASK INTERFACES ---\n'
    printf '#define VOX_TASK(name, prefix) \\\n'
    printf '    static inline void prefix##_boot(VoxEventBusTransmit transmit); \\\n'
    printf '    static inline void prefix##_terminate(void); \\\n'
    printf '    static inline void prefix##_run(float delta_time); \\\n'
    printf '    static inline bool prefix##_on_event_bus(const int type, const void* payload, const int size, const char* source);\n\n'

    # Stack
    printf '#define VOX_TASK_STACK \\\n'
    for task in "${TASKS[@]}"; do
        # name and prefix are the same (e.g. task_ui_terminal_desktop)
        printf '    VOX_TASK(%s, %s) \\\n' "$task" "$task"
    done
    printf '\n'
    printf 'VOX_TASK_STACK\n'
    printf '#undef VOX_TASK\n\n'

    #  Includes
    printf '// --- AUTO-INCLUDES ---\n'
    for task in "${TASKS[@]}"; do
        printf '#include "%s.c"\n' "$task"
    done
    
} > vox_autogen.c

# Compile | Save to file
BUILD_COMMAND="clang microkernel.c -o \"../Build/$BUILD_NAME\" $FLAGS $BUILD_MODE_FLAGS"
echo "$BUILD_COMMAND" > "../build.log"
eval $BUILD_COMMAND >> "../build.log" 2>&1

# Final Check
if [ $? -eq 0 ]; then
    echo "Build successful! Ready to boot."
    exit 0
else
    echo -e "Build failed! Check build.log for details.\n"
    exit 1
fi